apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: localhost/apptodo 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db_config
              key: host

        - name: DB_USERNAME
          valueFrom:
          secretKeyRef:
              name: db_config
              key: username

        - name: DB_PASSWORD
          valueFrom:
          secretKeyRef:
            name: db_secret
            key: password

        - name: DB_PORT
          valueFrom:
          configMapKeyRef:
              name: db_config
              key: port