apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgdb
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:14.4-bullseye
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
            secretKeyRef:
                name: db_config
                key: username

          - name: POSTGRES_PASSWORD
            valueFrom:
            secretKeyRef:
              name: db_secret
              key: password
